name: ${project.name}
author: ${project.organization.name}
version: ${project.version}
main: ${project.main}
api-version: 1.14

commands:
  challenge:
    aliases:
      - sneakyEntity
      - sneakyEntities
    usage: /<command> <start/stop/toggleFail>
    description: Command to setting up your challenge.